### ISSUE TITLE
3.3.1 precompiled binary crashes on older laptop 

### ISSUE THREAD

**Issue by hanslub42** [SRI-CSL/Maude#8]
When running the binary from version 3.3.1 `Maude-linux.zip` I get 

     Maude internal error

Upon further investigation with `strace` this turns out to be caused by a `SIGILL` signal. `gdb` shows the relevant illegal instruction to be a `mulx` which  was first introduced in 2013 with Haswell, when my laptop was already two years old.

- The binaries for previous versions of `maude` didn't have this problem
- When compiling from source everything is fine (of course)

So, not a big deal, but I don't  expect much performance would be lost by having precompiled binaries run on older hardware.

**Comment by stevenmeker** [comment]
This should be fixed in the Public alpha 146 release. I now build the Linux release on an old Haswell machine to have older libraries for better compatibility but it turns out that the default configuration for GNU GMP on this machine is Haswell specific, whereas on the newer machine which I used to use, it is generic x86_64.
